#!/bin/bash

# Directory structure:
#
# $PREFIX/ 
#   -> bin/*			  		: this sh script.
#   -> lib/cult-panel/*		: the cult module with all the classes we need.
#   -> share/cult-panel/*	: default config/theme files.
#
# $XDG_CONFIG_HOME/
#   -> cult-panel/			: the various config files we need.
#   -> cult-panel/themes	: all user-installed theme things.

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
MODULE_DIR="$MY_DIR/../lib/cult-panel"
export PYTHONPATH=$PYTHONPATH:$MODULE_DIR

# Run the panel!
exec $MODULE_DIR"/main.py" "$@"
